# Generated by Django 5.1.3 on 2024-11-05 12:14

import EmailApp.customFields.file_upload
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('password', models.CharField(max_length=100)),
                ('license', EmailApp.customFields.file_upload.LicenseFileField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
